Add react and webpack
ventilooo/ring-electron-client pull request #3
Opened 2017-05-19 20:35 UTC by ephelip

2017-05-23 13:36 UTC, ssirois approved these changes
This goes flawless on my side (testing under GNU/Linux).

Do we expect this pull request to have the desired behaviour on proprietary platforms as well (Microsoft Windows, Mac osX)?

If so, can someone test it? I don't have access to those things.

2017-05-24 15:53 UTC, ventilooo requested changes
Perfect on windows.
Just add a section in the README.md with the right links to install yarn and nvm on windows.

2017-05-25 15:03 UTC, ephelip commented
@ventilooo done, also added a section for macOS

2017-05-26 13:17 UTC, ventilooo approved these changes

2017-05-26 13:18 UTC, merged